
background_opacity         0.85


background_blur            1

background                 #181c1b
foreground                 #cbd5d0
cursor                     #7c8f85
selection_background       #35413d
selection_foreground       #cbd5d0


# Black (Тени хвои)
color0 #181c1b
color8 #2d3634

# Red (Заглушенный, как ягоды в тумане)
color1 #8b6868
color9 #a67d7d

# Green (Главный цвет: холодная хвоя и мох)
color2  #5e7068
color10 #7c8f85

# Yellow (Блеклое солнце сквозь тучи)
color3  #a8a18f
color11 #c9c1ac

# Blue (Холодный воздух/река)
color4  #6a7d82
color12 #889da3

# Magenta (Сумерки в лесу)
color5  #7a7282
color13 #968ca0

# Cyan (Ледяной ручей)
color6  #748b83
color14 #92aea4

# White (Сам туман)
color7  #cbd5d0
color15 #e3ece8

# Оформление окна
window_padding_width 20
confirm_os_window_close 0

