add_newline = true # Добавим пустую строку перед промптом для "воздуха"

# Формат: Первая строка с инфой, затем перенос и символ ввода
format = """
[](#6c8c72)\
[ ](bg:#6c8c72 fg:#121615)\
[](fg:#6c8c72 bg:#2e463a)\
$directory\
[](fg:#2e463a bg:#3a5f3c)\
$git_branch\
$git_status\
[](fg:#3a5f3c)\
$line_break\
$character"""

[directory]
style = "bg:#2e463a fg:#cbd5d0"
format = "[ $path ]($style)"
truncation_length = 3
fish_style_pwd_dir_length = 1

[git_branch]
symbol = " "
style = "bg:#3a5f3c fg:#cbd5d0"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "bg:#3a5f3c fg:#cbd5d0"
format = "[($all_status$ahead_behind )]($style)"

[line_break]
disabled = false

[character]
# Символ ввода на второй строке, чуть с отступом
success_symbol = " [󰄾](bold #6c8c72) "
error_symbol = " [󰄾](bold #a54242) "
